# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-16 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170516_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorprofile',
            options={'verbose_name': '\u4f5c\u8005\u4fe1\u606f', 'verbose_name_plural': '\u4f5c\u8005\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment', verbose_name='\u8bc4\u8bba'),
        ),
    ]
