# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-17 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170517_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='digest',
            field=models.TextField(max_length=100, verbose_name='\u6458\u8981'),
        ),
    ]
