# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-17 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='article',
            field=models.ManyToManyField(blank=True, to='blog.Article', verbose_name='\u6587\u7ae0'),
        ),
    ]
